INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (1, 1, 'Overkill', '00:05:14', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (2, 2, 'Stay Clean', '00:02:40', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (3, 3, '(I Won''t) Pay Your Price', '00:02:56', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (4, 4, 'I''ll Be Your Sister', '00:02:52', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (5, 5, 'Capricorn', '00:04:09', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (6, 6, 'No Class', '00:02:38', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (7, 7, 'Damage Case', '00:03:02', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (8, 8, 'Tear Ya Down', '00:02:40', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (9, 9, 'Metropolis', '00:03:36', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (10, 10, 'Limb From Limb', '00:04:54', 1);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (11, 1, 'And Hell Will Follow Me', '00:00:57', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (12, 2, 'As Black As My Heart', '00:04:32', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (13, 3, 'To Die In Your Arms', '00:03:36', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (14, 4, 'Heroin Train', '00:03:10', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (15, 5, 'Devil in the Closet', '00:03:42', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (16, 6, 'Cracks in the Walls', '00:05:40', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (17, 7, 'Bad Dream', '00:02:06', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (18, 8, 'Bath in My Blood (Schizophrenia in Me)', '00:02:25', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (19, 9, 'Pill Head', '00:05:38', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (20, 10, 'Meet the Wolf', '00:05:27', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (21, 11, 'Serial Killer', '00:04:38', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (22, 12, 'When the Crows Descend Upon You', '00:04:11', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (23, 13, 'Die Alone', '00:07:35', 3);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (24, 1, 'Mirror Reaper', '01:23:15', 5);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (25, 1, 'The Great Filter', '00:21:33', 7);
INSERT INTO MusicDB.Track (Track_ID, Track_Number, Track_Name, Track_Length, Album_ID) VALUES (26, 1, 'Type III', '00:18:40', 8);